# Generated by Django 5.0.6 on 2024-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa', models.IntegerField()),
                ('locuri', models.IntegerField()),
                ('meniu', models.CharField(choices=[('OMNI', 'Omnivor'), ('VEG', 'Vegetarian'), ('PESC', 'Pescatarian')], max_length=16)),
            ],
        ),
    ]
