# Generated by Django 5.0.6 on 2024-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masa',
            name='locuri',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='meniu',
        ),
        migrations.AlterField(
            model_name='masa',
            name='masa',
            field=models.CharField(choices=[('M1', 'Masa 1'), ('M2', 'Masa 2')], max_length=7),
        ),
    ]
