# Generated by Django 5.0.6 on 2024-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0003_rezervare'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rezervare',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='rezervare',
            unique_together={('masa', 'check_in')},
        ),
    ]
