# Generated by Django 5.0.6 on 2024-09-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0004_masa_price_rezervare_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezervare',
            unique_together=set(),
        ),
    ]
