# Generated by Django 5.0.6 on 2024-09-11 15:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0005_alter_rezervare_unique_together'),
    ]

    operations = [
    ]

from django.db import migrations

def remove_duplicate_reservations(apps, schema_editor):
    Rezervare = apps.get_model('rezervare', 'Rezervare')
    duplicates = (
        Rezervare.objects.values('masa_id', 'check_in')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        # Keep one and delete the rest
        Rezervare.objects.filter(
            masa_id=duplicate['masa_id'], 
            check_in=duplicate['check_in']
        ).order_by('id')[1:].delete()  # Keep the first, delete the others

class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0004_masa_price_rezervare_price_and_more'),  # Adjust to your previous migration
    ]

    operations = [
        migrations.RunPython(remove_duplicate_reservations),
    ]