# Generated by Django 5.0.6 on 2024-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0005_alter_rezervare_unique_together'),
        ('rezervare', '0006_auto_20240911_1503'),
    ]

    operations = [
    ]
