# Generated by Django 5.0.6 on 2024-09-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0007_merge_20240911_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezervare',
            unique_together={('masa', 'check_in')},
        ),
    ]
