# Generated by Django 5.0.6 on 2024-09-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervare', '0008_alter_rezervare_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezervare',
            unique_together=set(),
        ),
    ]
